server:
  port: 8888
  servlet:
    context-path: /center


eureka:
  instance:
      hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/center/eureka

