server:
  port: 9000
  servlet:
    context-path: /center

eureka:
  instance:
    hostname: 120.92.42.252
    prefer-ip-address: true
    ip-address: 120.92.42.252
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

