server:
  port: 9000
  servlet:
    context-path: /center

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${server.port}