eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 9998
spring:
  application:
    name: service-feign

#ribbon的超时时间,不设置默认是一秒超时
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000