eureka:
  client:
    serviceUrl:
      defaultZone: http://120.92.42.252:9000/center/eureka/
server:
  port: 9040
spring:
  application:
    name: service-ribbon
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#    pool:
#      enabled: false
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
